---
title: "Challenge 7_New"
author: "Wong Wei Qi"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>
```{r, eval=TRUE,echo=TRUE}
library(tidyverse)
library(palmerpenguins)
glimpse(penguins)

```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_depth_mm,
    y = bill_length_mm,
    colour = species
  )
) +
  geom_point() +
  labs(title = "Bill depth and length", subtitle = "Dimensions for Adelie Chinstrap and Gentoo Penguins", x = "Bill depth (mm)", y = "Bill length (mm)", colour = "Species", caption = "Source: Palmer Station LTER/palmerpenguin package") +
scale_colour_viridis_d()
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(penguins, aes(
  x = bill_depth_mm, y = bill_length_mm, colour = species,
  shape = species, size = body_mass_g, alpha = flipper_length_mm
)) +
  geom_point() +
  scale_colour_viridis_d()

```

### Facet 1
<br>
```{r, eval=TRUE,echo=TRUE}

ggplot(penguins) +
  aes(
    x = bill_depth_mm,
    y = bill_length_mm
  ) +
  geom_point() +
  facet_grid(species ~ island)
```
### Facet 2
<br>
```{r, eval=TRUE,echo=TRUE}

ggplot(penguins) +
  aes(
    x = bill_depth_mm,
    y = bill_length_mm
  ) +
  geom_point() +
  facet_grid(species ~ sex)
```
### Facet 3
<br>
```{r, eval=TRUE,echo=TRUE}

ggplot(penguins) +
  aes(
    x = bill_depth_mm,
    y = bill_length_mm
  ) +
  geom_point() +
  facet_grid(sex ~ species)
```

### Facet 4
<br>
```{r, eval=TRUE,echo=TRUE}

ggplot(penguins) +
  aes(
    x = bill_depth_mm,
    y = bill_length_mm
  ) +
  geom_point() +
  facet_wrap(~species)
```
### Facet 5
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_wrap(~ species, ncol = 2)
```

### Facet 6
<br>

```{r, eval=TRUE,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
facet_grid(. ~ species)
```
```{r, eval=TRUE,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d()
```
<br>
```{r, eval=TRUE,echo=TRUE}
library(openintro)
glimpse(loans_full_schema)
```
<br>
```{r, eval=TRUE,echo=TRUE}
loans <- loans_full_schema %>%
select(loan_amount, interest_rate, term, grade,
state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```

<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
geom_histogram(binwidth = 5000, alpha = 0.5) +
labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans")
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = loan_amount, fill = homeownership)) + geom_histogram(binwidth = 5000) +
labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
facet_wrap(~ homeownership, nrow = 3)
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = loan_amount)) +
geom_density(adjust = 1)
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
geom_density(adjust = 2, alpha = 0.5) +
labs (x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeowner")
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
title = "Interest rates of Lending Club loans") +
theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = interest_rate,
y = grade)) +
geom_boxplot() +
labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle = "by grade of loan")
```

<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
geom_hex()
```
<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans %>% filter(debt_to_income < 100),
aes(x = debt_to_income, y = interest_rate)) +
geom_hex()
```

<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = homeownership,
fill = grade)) +
geom_bar()
```

<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = homeownership, fill = grade)) +
geom_bar(position = "fill")
```

<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(y = homeownership, fill = grade)) + geom_bar(position = "fill") +
labs( x = "Proportion", y = "Homeownership", fill = "Grade", title = "Grades of Lending Club loans")
```

<br>
```{r, eval=TRUE,echo=TRUE}
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
geom_violin()
```

<br>
```{r, eval=TRUE,echo=TRUE}
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) +
geom_density_ridges(alpha = 0.5)
```

